### ISSUE TITLE
KeyError: 'module name can't contain "."'

### ISSUE THREAD

**Issue by zhixuanli** [DeepMotionAIResearch/DenseASPP#7]
>Traceback (most recent call last):
  File "/home/oliver/PycharmProjects/semantic-segmentation-pytorch/DenseASPP/demo.py", line 18, in <module>
    infer = Inference(args.model_name, args.model_path)
  File "/home/oliver/PycharmProjects/semantic-segmentation-pytorch/DenseASPP/inference.py", line 28, in __init__
    self.seg_model = self.__init_model(model_name, model_path, is_local=False)
  File "/home/oliver/PycharmProjects/semantic-segmentation-pytorch/DenseASPP/inference.py", line 50, in __init_model
    seg_model = DenseASPP(Model_CFG, n_class=N_CLASS, output_stride=8)
  File "/home/oliver/PycharmProjects/semantic-segmentation-pytorch/DenseASPP/models/DenseASPP.py", line 40, in __init__
    bn_size=bn_size, growth_rate=growth_rate, drop_rate=drop_rate)
  File "/home/oliver/PycharmProjects/semantic-segmentation-pytorch/DenseASPP/models/DenseASPP.py", line 188, in __init__
    bn_size, drop_rate, dilation_rate=dilation_rate)
  File "/home/oliver/PycharmProjects/semantic-segmentation-pytorch/DenseASPP/models/DenseASPP.py", line 166, in __init__
    self.add_module('norm.1', bn(num_input_features)),
  File "/home/oliver/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 180, in add_module
    raise KeyError("module name can't contain \".\"")
KeyError: 'module name can\'t contain "."'

Environment:
+ pytorch 1.0.1
+ Cuda 10.1

After reading this link: [https://github.com/taey16/pix2pixBEGAN.pytorch/issues/7](https://github.com/taey16/pix2pixBEGAN.pytorch/issues/7), I'm wondering whether replacing is the only way to solve this problem?

Can you give me some advice?

Thank you so much!

**Comment by zhixuanli** [comment]
I have repaired it by hand :smile:

**Comment by nefelipk** [comment]
I tried the same thing but I am getting RuntimeError. 
You just removed "." ?
So now norm.1 is norm?

**Comment by 70kg** [comment]
@zhixuanli how to fix it?

**Comment by 70kg** [comment]
@nefelipk  Did you solve this problem？

**Comment by nefelipk** [comment]
> @nefelipk Did you solve this problem？
 I didn't.

**Comment by nefelipk** [comment]
> @nefelipk Did you solve this problem？

I didn't

**Comment by stone100010** [comment]
Change the file path
